### Hämta en användares favoritbilder
# Notera: Ersätt 'username' med faktiskt användarnamn i din databas
GET http://localhost:3001/api/user/username/favorites

### Spara en användares favoritbild
POST http://localhost:3001/api/user/savepic
Content-Type: application/json

{
  "user": "userExample",
  "favoritePics": [
    {
      "title": "picture1",
      "byteSize": 1000,
      "url": "https://www.google.com"
    }
  ]
}
