
# GET http://localhost:3001/pics

POST http://localhost:3001/api/user/savepic
Content-type: application/json 

   
      {
        "title": "picture1",
        "byteSize": 1000,
        "url": "https://www.google.com"
      }
