GET http://localhost:3000/users/exampleID/favorites

### Spara en användares favoritbild
POST http://localhost:3000/users/
Content-Type: application/json

{
  "userId": "exampleID",
  "favorites": [
    {
      "title": "picture1",
      "byteSize": 1000,
      "link": "https://www.google.com"
    }
  ]
}
